title: The story of a ch(a)rt library
email: sayhi@chrt.io
description: >- # this means to ignore newlines
  We are building a new fun to use javascript library for data visualization.
domain: blog.chrt.io
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://blog.chrt.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chrt_io
github_username:  chrt-io
nonav: 1 # hide navigation for chrt blog

permalink: /:categories/:slug

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
