title: Chrt Blog | The story of a ch(a)rt library
email: sayhi@chrt.io
description: >- 
  We are building a new fun to use javascript library for data visualization.
keywords: >-
  chrt, chrt.io, library, charting library, javascript, data visualization, dataviz
domain: blog.chrt.io
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://blog.chrt.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: G-1YTRCQ8L2P
logo: /assets/images/logo.png


# Build settings
plugins:
#  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: archive
  tag: '/archives/:name/'

permalink: /:year/:month/:day/:title:output_ext

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
